### PR TITLE
Initial baseline model with timeseries forecasting ARIMA model and fl…

### PR DESCRIPTION
**Pull request by helenjli**
This contains a colab file with our time series forecasting ARIMA model and the flight data csv. More comments will be added in my personal progress report but feel free to comment on where the colab could use some more work.

The baseline model only looks at one airport at a time but you can set it to any other airport. Some big limitations of time series forecasting is that it can only work with one airport at a time (for now) and even that takes 30 seconds to train over about 80 weeks.

### CODE REVIEW

**Review by BrenoPin — APPROVED** [review]

**Comment by ArashAhmadian** [comment]
@helenjli it's hard to look at the code if it's in .ipynb format. Also, you can't run the scripts directly from the command line I think as it's just parsed as a json file.

**Comment by ArashAhmadian** [comment]
But the code looks good. If you could make push the files in .py format it would be ideal :)

**Comment by helenjli** [comment]
@ArashAhmadian It's a google colab file instead of a script, is that fine for baseline? It's much easier to edit and see graphs that way. I can upload the HTML too!

**Comment by helenjli** [comment]
will upload .py as well for all 3 ^

**Review by ArashAhmadian — CHANGES_REQUESTED** [review]
will merge once you add the other files.

**Comment by ArashAhmadian** [comment]
LGTM

**Pull request merged**
